- name: twitter
  platform: twitter
  consumer_key: !secret twitter_consumer_key
  consumer_secret: !secret twitter_consumer_secret
  access_token: !secret twitter_access_token
  access_token_secret: !secret twitter_access_token_secret

- name: email_main
  platform: smtp
  server: smtp.gmail.com
  port: 587
  timeout: 15
  sender: !secret email_smtp_user
  encryption: starttls
  username: !secret email_smtp_user
  password: !secret email_smtp_password
  recipient:
    - !secret email_primary_recipient
  sender_name: Home Assistant
