- platform: mqtt
  name: "Basement Front Lights"
  icon: mdi:ceiling-light
  state_topic: "stat/bsmt-front/POWER"
  command_topic: "cmnd/bsmt-front/POWER"
  availability_topic: "tele/bsmt-front/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false

- platform: mqtt
  name: "Basement Back Lights"
  icon: mdi:ceiling-light
  state_topic: "stat/bsmt-back/POWER"
  command_topic: "cmnd/bsmt-back/POWER"
  availability_topic: "tele/bsmt-back/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false

- platform: mqtt
  name: "Backyard Remote"
  icon: mdi:remote
  state_topic: "stat/backyard-remote/POWER"
  command_topic: "cmnd/backyard-remote/POWER"
  availability_topic: "tele/backyard-remote/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false

- platform: command_line
  scan_interval: 120
  switches:
    frontcam_motion:
      friendly_name: Front Cam Motion Alerts
      command_on: !secret frontcam_enable
      command_off: !secret frontcam_disable
      command_state: !secret frontcam_state
