- platform: mqtt
  name: "Basement Lights"
  icon: mdi:ceiling-light
  state_topic: "stat/bsmt-front/POWER"
  command_topic: "cmnd/bsmt-front/POWER"
  availability_topic: "tele/bsmt-front/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false

- platform: mqtt
  name: "Backyard Remote"
  icon: mdi:remote
  state_topic: "stat/backyard-remote/POWER"
  command_topic: "cmnd/backyard-remote/POWER"
  availability_topic: "tele/backyard-remote/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false

- platform: mqtt
  name: "Garage North"
  icon: mdi:garage
  state_topic: "stat/garage/north"
  command_topic: "cmnd/garage/north"
  payload_on: "relay"
  payload_off: "relay"
  state_off: '{"state": "closed"}'
  state_on: '{"state": "open"}'
  qos: 1
  retain: false

- platform: mqtt
  name: "Garage South"
  icon: mdi:garage
  state_topic: "stat/garage/south"
  command_topic: "cmnd/garage/south"
  payload_on: "relay"
  payload_off: "relay"
  state_off: '{"state": "closed"}'
  state_on: '{"state": "open"}'
  qos: 1
  retain: false

